controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix: front_

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix: admin_
    prefix: /admin/
